export default {
  id: "workbuddy",
  alias: "wb",
  uiAlias: "wb",
  priority: 90,
  display: {
    name: "WorkBuddy",
    icon: "work",
    color: "#006EFF",
    website: "https://www.workbuddy.ai",
    notice: { signupUrl: "https://www.workbuddy.ai" },
  },
  category: "oauth",
  authModes: ["oauth"],
  hasOAuth: true,
  transport: {
    baseUrl: "https://www.workbuddy.ai/v2/chat/completions",
    forceStream: true,
    thinkingFormat: "openai",
    defaultSystemPrompt: "You are a helpful AI assistant.",
    product: "SaaS",
    billingAccept: "application/json",
    headers: {
      "User-Agent": "CLI/2.108.1 CodeBuddy/2.108.1",
      "X-Product": "SaaS",
      "X-IDE-Type": "CLI",
      "X-IDE-Name": "CLI",
      "X-Requested-With": "XMLHttpRequest",
      "x-codebuddy-request": "1",
      Origin: "https://www.workbuddy.ai",
      Referer: "https://www.workbuddy.ai/",
    },
    auth: {
      combined: true,
      header: "Authorization",
      scheme: "bearer",
      hooks: ["workbuddyIdentity"],
    },
    usage: { url: "https://www.workbuddy.ai/v2/billing/meter/get-user-resource" },
  },
  // Catalog mirrors the CLI product-config payload (deploymentType SaaS, platform
  // CLI). Every id below was probed against a connected account on 2026-09-20 and
  // answered 200, so the list is what this gateway actually serves.
  models: [
    { id: "default-model", name: "Auto" },
    { id: "fast-model", name: "Fast" },
    { id: "balanced-model", name: "Balanced" },
    { id: "primary-model", name: "Primary" },
    { id: "deep-model", name: "Deep" },
    { id: "hy4-preview", name: "Hy4 Preview" },
    { id: "hy3", name: "Hy3" },
    { id: "gpt-5.6-sol", name: "GPT-5.6-Sol" },
    { id: "gpt-5.6-terra", name: "GPT-5.6-Terra" },
    { id: "gpt-5.6-luna", name: "GPT-5.6-Luna" },
    { id: "gpt-5.5", name: "GPT-5.5" },
    { id: "gpt-5.4", name: "GPT-5.4" },
    { id: "gpt-5.3-codex", name: "GPT-5.3-Codex" },
    { id: "gemini-3.5-flash", name: "Gemini-3.5-Flash" },
    { id: "glm-5.3", name: "GLM-5.3" },
    { id: "glm-5.2", name: "GLM-5.2" },
    { id: "kimi-k3", name: "Kimi-K3" },
    { id: "kimi-k2.6", name: "Kimi-K2.6" },
  ],
  oauth: {
    baseUrl: "https://www.workbuddy.ai",
    stateUrl: "https://www.workbuddy.ai/v2/plugin/auth/state",
    tokenUrl: "https://www.workbuddy.ai/v2/plugin/auth/token",
    accountUrl: "https://www.workbuddy.ai/v2/plugin/login/account",
    refreshUrl: "https://www.workbuddy.ai/v2/plugin/auth/token/refresh",
    userAgent: "CLI/2.63.2 CodeBuddy/2.63.2",
    platform: "CLI",
    pollInterval: 5000,
  },
  features: { usage: true },
};
